name: Build and Deploy
on:
  push:
    branches: [master]
  workflow_run:
    workflows: ["Pull Resume"]
    types:
      - completed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build and Export
        run: |
          yarn install --frozen-lockfile
          yarn export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: rgoulazian.com
