name: Pull Resume
on:
  schedule:
    # Pulls daily at midnight EST
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  pull-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Download Resume
        run: wget -O resume.pdf https://drive.google.com/uc?export=download&id=19UZvcNgGWA2BiM4MUndADQFZVUPYPbdX
      - name: Commit New Resume
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update resume
          branch: ${{ github.head_ref }}
