name: Pull Resume
on:
  # schedule:
  # Pulls daily at midnight EST
  # - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  pull-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Download Resume
        run: wget --no-check-certificate 'https://onedrive.live.com/download?cid=9EE6ED4528986B5D&resid=9EE6ED4528986B5D%2161354&authkey=AIS5kld_1eAQNaI&em=2' -O public/resume.pdf
      - name: Commit New Resume
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update resume
          branch: ${{ github.head_ref }}
